### PR TITLE
Clean nba stat data

### LINKED ISSUE #4: Clean data retrieved from NBADataLoader
Not all of the columns in the dataframe will be required for the analysis. 

Removed both redundant and unneeded columns. The cleanser could probably be used as a step within the getPlayerSeasonalBoxData() method of NBADataLoader.

### PR DESCRIPTION
**Pull request by darkhark**
Output
```
    GAME_DATE  PlusMinusPoints  PlusMinusAcc
0  2020-08-13        -8.343284      0.024735
1  2020-08-10         3.656716     -0.022884
2  2020-08-08         5.656716      0.000926
3  2020-08-05        -6.343284     -0.124074
4  2020-08-03        -3.343284      0.066143
..        ...              ...           ...
62 2019-11-01        13.656716      0.105577
63 2019-10-29        -2.343284      0.056481
64 2019-10-27        -5.343284      0.091835
65 2019-10-25         6.656716      0.089161
66 2019-10-22        -7.343284     -0.106217
```

Will handle the 2019-2020 season after. That season is going to require special attention altogether. It may honestly be worth ignoring that season or else we, well I guess I lol, will have to deal with writing something out for that one season and I don't know if the extra time to do that is worth it. I guess it wouldn't take too long... 

If we decide to use the 19-20 season, I'll write something for it later.

### CODE REVIEW

**Comment by darkhark** [comment]
The cleanser also returns the average accuracy and average points, which the NBAPlayer will store for future reference.

**Comment by darkhark** [comment]
I'll add some documentation too.

**Comment by darkhark** [comment]
Ready

**Review by afandino — APPROVED** [review]
I learned from your code about return value annotations and documenting parameters

**Comment by darkhark** [comment]
Awesome, good to hear!

**Pull request merged**
