### PR TITLE
Twitter data cleaner

### LINKED ISSUE #5: Clean Twitter Data
Once the twitter data is available, clean it up. Remove stopping words, maybe special characters, etc. Will need more discussion.

### PR DESCRIPTION
**Pull request by darkhark**

### CODE REVIEW

**Comment by darkhark** [comment]
Can be tested using something like. 
```
tweetsDF = tdl.getPlayerTweetsAsDF('KingJames', '2020-08-01', '2020-08-07')
tweetsDF = cleanTweets(tweetsDF)
print(tweetsDF)
```

**Review by el-grudge — COMMENTED** [review]
a few notes about text cleaner:

* what do you think we should do about mentions/hashtags? i suggest removing them, but i don't have a strong argument for that, its just a standard practice i guess. you could use something like this: 
```
# remove mentions
cleanDF.tweet = cleanDF.tweet.str.replace(r"@[A-Za-z0-9]+", "")
# remove hashtags
cleanDF.tweet = cleanDF.tweet.str.replace(r"#[A-Za-z0-9]+", "")
```

* also, in some cases cleaning the text result in an empty string, so we'll need to deal with that. i suggest dropping these rows

```
cleanDF.tweet.replace('', np.nan, inplace=True)
cleanDF.dropna(subset=['tweet'], inplace=True)
```

**Comment by darkhark** [comment]
@el-grudge Yeah, I agree on both accounts. I initially had the code in to remove empty tweets then deleted it for no reason lol. I thought about removing the hashtags and mentions too but wanted your opinions first. I think it's good to remove them because it's not easily possibly to break up the hashtags into actual words we can use for analysis.

**Comment by darkhark** [comment]
Okay, now it's ready lol

**Comment by afandino** [comment]
Yes I agree

**Review by afandino — COMMENTED** [review]
looks good

**Comment by darkhark** [comment]
@afandino you closed the PR without merging it lol

**Comment by darkhark** [comment]
I think you just have to approve it and then anyone can merge it.

**Review by el-grudge — APPROVED** [review]
looks good

**Pull request merged**
